#!/bin/bash

#$ -S /bin/bash

#$ -wd /home/bgaujac/tdwae

#$ -l gpu=1
#$ -l tmem=4G
#$ -l h_rt=100:00:00

#$ -t 1-36

#$ -N mnist_4ldet_wae_multi

source /share/apps/examples/source_files/python/python-3.6.4.source
source /share/apps/examples/source_files/cuda/cuda-9.0.source


#python3 run_onelayer_wae.py --lmba 1. --work_dir 1l_mnist
python3 run_array.py --enet_archi mlp_one_layer --dnet_archi mlp_one_layer --params $SGE_TASK_ID --work_dir 4ldet_mnist_exp$SGE_TASK_ID
