#!/bin/bash

#$ -S /bin/bash

#$ -wd /home/bgaujac/tdwae

#$ -l gpu=True
#$ -l tmem=4G
#$ -l h_rt=20:00:00

#$ -t 1-18

#$ -N mnist_icml

source /share/apps/examples/source_files/python/python-3.6.4.source
source /share/apps/examples/source_files/cuda/cuda-9.0.source


#python3 run_onelayer_wae.py --lmba 1. --work_dir 1l_mnist
python3 run_mnist_array.py --work_dir 5l_mnist_v4_$SGE_TASK_ID --exp_id $SGE_TASK_ID
