#!/bin/bash

#$ -S /bin/bash

#$ -wd /home/bgaujac/tdwae

#$ -l gpu=1
#$ -l tmem=2G
#$ -l h_rt=00:30:00


#$ -N tensorflow_version
#$ -P gpu

source /share/apps/examples/python/python-3.6.5.source
source /share/apps/examples/cuda/cuda-9.0.source


LD_LIBRARY_PATH="/share/apps/libc6_2.23/lib/x86_64-linux-gnu:/share/apps/libc6_2.23/lib64:/share/apps/gcc-6.2.0/lib64:/share/apps/gcc-6.2.0/lib:/share/apps/python-3.6.5-shared/lib:/share/apps/cuda-9.0/lib64:${LD_LIBRARY_PATH}" /share/apps/libc6_2.23/lib/x86_64-linux-gnu/ld-2.23.so $(command -v /share/apps/python-3.6.5-shared/bin/python3) -c 'import tensorflow as tf; print(tf.__version__)'
